# WIDTH = 576
# HEIGHT = 576

# SCREEN_WIDTH = 700
# SCREEN_HEIGHT = 577
# DIMENSION = 9
# CELL_SIZE = 38 # = 64
# GRID = (64,84,46)
#BUT_WIDTH = BUT_HEIGHT = 50

WIDTH = 720
HEIGHT = 720

SCREEN_WIDTH = 875
SCREEN_HEIGHT = 721
DIMENSION = 9
CELL_SIZE = 47.5 # = 64
GRID = (80,105,57.5)

MAX_FPS = 15
BUT_WIDTH = BUT_HEIGHT = 62.5
BACKWARD_X = WIDTH
BACKWARD_Y = HEIGHT/2 - BUT_HEIGHT/2

NEXTSTEP_X = SCREEN_WIDTH - BUT_WIDTH
NEXTSTEP_Y = HEIGHT/2 - BUT_HEIGHT/2

REVERSE_X =SCREEN_WIDTH - BUT_WIDTH - BUT_WIDTH + 15
REVERSE_Y = HEIGHT/2 - BUT_HEIGHT/2 - BUT_WIDTH

START_X = WIDTH/2 - BUT_WIDTH/2 
START_Y = HEIGHT/2 - BUT_HEIGHT/2


REPLAY_X = SCREEN_WIDTH - BUT_WIDTH- BUT_WIDTH +15
REPLAY_Y = HEIGHT/2 - BUT_HEIGHT/2 + BUT_WIDTH
# s.WIDTH/2 - textSurface.get_width()/2, s.SCREEN_HEIGHT/2 - textSurface.get_height()/2))